modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPL-3.0-ONLY, MIT"

[[mods]]
modId = "archvillagehealthcare"
version = "${version}"
displayName = "Village HealthcareEx"
authors = "BigDenseHedge, HyperPigeon"
description = '''
A port of the village healthcare mod to Architectury.
'''
logoFile = "icon.png"

[[mixins]]
config = "archvillagehealthcare.neoforge.mixins.json"

[[mixins]]
config = "archvillagehealthcare.common.mixins.json"

[[dependencies.archvillagehealthcare]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archvillagehealthcare]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.4]"
ordering = "NONE"
side = "BOTH"